#!/usr/bin/env python

import rospy
from std_msgs.msg import String

def callback(data):
    global times
    times+=1
    rospy.loginfo(rospy.get_caller_id()+'I heard %s', data.data + str(times))
    if int(times)%5==0:
        pub_func()        

def listener():
    global times
 
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber('chatter',String,callback)
    rospy.spin()

def pub_func():
    pub=rospy.Publisher('feedback',String,queue_size=10)
   #rospy.init_node('talker',anonymous=True)
    rospy.loginfo("sanding massage....\n\n\n\n")
    pub.publish("*****OK******")


if __name__=='__main__':
    times=0
    listener()