#!/usr/bin/env python

import rospy
from std_msgs.msg import String
def callback(data):
    rospy.loginfo(data.data)

def talker():
    rospy.Subscriber('feedback',String,callback)
    pub=rospy.Publisher('chatter',String,queue_size=10)
    rospy.init_node('talker',anonymous=True)
    rate=rospy.Rate(1)
    while not rospy.is_shutdown():
        hello_str="hello world, %s" % "i'm talker"  #str(rospy.get_time())
        rospy.loginfo(hello_str)
        pub.publish(hello_str)


        rate.sleep()

if __name__=='__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
